export default {
  NODEMAILER_SENDER_EMAIL: process.env.NODEMAILER_SENDER_EMAIL,
  RABBITMQ_HOST: process.env.RABBITMQ_HOST,
  RABBITMQ_PORT: Number(process.env.RABBITMQ_PORT) || 5672,
  RABBITMQ_USERNAME: process.env.RABBITMQ_USERNAME,
  RABBITMQ_PASSWORD: process.env.RABBITMQ_PASSWORD,
  NODEMAILER_HOST: process.env.NODEMAILER_HOST,
  NODEMAILER_PORT: Number(process.env.NODEMAILER_PORT) || 1025,
}